### PR TITLE
Add android 13 support

### PR DESCRIPTION
**Pull request by haridhayal11**
Tested & confirmed to be working on Android 13.
Needs testing to check if it breaks previous Android versions. The apk can be downloaded from [here](https://github.com/haridhayal11/FakeGApps/releases/tag/13-alpha). Would be great if someone can test on previous android versions and confirm if it works properly.

### CODE REVIEW

**Comment by whew-inc** [comment]
Hello, thank you for the PR!

I believe this will break Android 12(.1) as `com.android.server.pm.ComputerEngine` does not exist on that version.

**Comment by haridhayal11** [comment]
> Hello, thank you for the PR!
> 
> I believe this will break Android 12(.1) as `com.android.server.pm.ComputerEngine` does not exist on that version.

I assumed that, maybe we can add a if statement to detect like you have done for 12 ?

**Comment by BigB84** [comment]
@haridhayal11 

I tested your apk on LOS20.
MicroG passes. 

Thanks.

**Comment by HritwikSinghal** [comment]
> Hello, thank you for the PR!
> 
> I believe this will break Android 12(.1) as `com.android.server.pm.ComputerEngine` does not exist on that version.

will this break it?

**Pull request merged**
